# Generated by Django 5.0 on 2024-07-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_speciality_alter_blogpost_summary_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
